# Generated by Django 4.2.7 on 2023-11-12 12:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_court_max_players_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='game_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=5400)),
        ),
        migrations.AddField(
            model_name='court',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='court_images/'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.court')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='timeslot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.timeslot'),
        ),
    ]
