# Generated by Django 4.2.7 on 2023-11-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_gamelevel_playertype_timeslot_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='canceled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
