# Generated by Django 4.2.7 on 2023-11-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_reservation_canceled_on_reservation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
