# Generated by Django 4.2.7 on 2023-11-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
