# Generated by Django 4.2.7 on 2023-11-14 21:28

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_court_options_alter_gamelevel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='federation_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
