# Generated by Django 4.2.7 on 2023-11-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_profile_federation_number_alter_reservation_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='block_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
