# Generated by Django 4.2.7 on 2023-11-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_reservation_block_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='block_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_1', to='booking.reservation'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='block_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_2', to='booking.reservation'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='block_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_3', to='booking.reservation'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='block_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_4', to='booking.reservation'),
        ),
    ]
