# Generated by Django 4.2.7 on 2023-11-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_timeslot_block_1_timeslot_block_2_timeslot_block_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='block_number',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='block_1',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='block_2',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='block_3',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='block_4',
        ),
    ]
