# Generated by Django 4.2.7 on 2023-11-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_reservation_master_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='master_reservation',
        ),
    ]
