# Generated by Django 4.2.7 on 2023-11-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_timeslot_full_court_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationtimeslotmaster',
            name='total_slot_count',
            field=models.IntegerField(default=0),
        ),
    ]
