# Generated by Django 4.2.7 on 2023-11-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_reservationtimeslotmaster_total_slot_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationtimeslotmaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
