# Generated by Django 4.2.7 on 2023-11-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_reservationtimeslotmaster_is_full_court_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='booking_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('full_court', 'Full Court')], default='individual', max_length=15),
        ),
    ]
