# Generated by Django 4.2.7 on 2023-11-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_timeslottemplate_booking_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='booking_type',
        ),
    ]
