# Generated by Django 4.2.7 on 2023-12-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_remove_timeslot_booking_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='gamelevel',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='playertype',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='tournamentregistration',
            options={'get_latest_by': 'modified'},
        ),
        migrations.RemoveField(
            model_name='court',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='court',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='court',
            name='status',
        ),
        migrations.RemoveField(
            model_name='gamelevel',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='gamelevel',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='gamelevel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='playertype',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='playertype',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='playertype',
            name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='status',
        ),
        migrations.AlterField(
            model_name='timeslottemplate',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.gamelevel'),
        ),
        migrations.AlterField(
            model_name='timeslottemplate',
            name='player_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.playertype'),
        ),
    ]
